---
abstract: 'detailed diagnostics for your reference tracking tests'
author:
  - 'Olivier Mengué <dolmen@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300030, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-DiagRef
recommends:
  Devel::FindRef: 0
requires:
  Test::More: 0
version: 1.130670
