---
abstract: 'detailed diagnostics for your reference tracking tests'
author:
  - 'Olivier Mengué <dolmen@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-DiagRef
recommends:
  Devel::FindRef: 0
requires:
  Exporter: 5.57
  Test::More: 0
  perl: 5
resources:
  homepage: https://github.com/dolmen/p5-Test-DiagRef
  repository: https://github.com/dolmen/p5-Test-DiagRef.git
version: 1.132080
